version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /idealsapp/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: idealsapp
      POSTGRES_DB: ideals

  adminer:
    image: adminer
    restart: always
    depends_on: [db]
    ports:
      - 8080:8080
